config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  get '/ticket_dates', to: 'tickets#ticket_dates'
end

app/models/additional_service_area_code.rb
class AdditionalServiceAreaCode < ApplicationRecord
end

app/models/adress_digsite.rb
class AdressDigsite < ApplicationRecord
end

app/models/adress_info.rb
class AdressInfo < ApplicationRecord
  belongs_to :adress_digsite
  belongs_to :street_digsite
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/digsite_info.rb
class DigsiteInfo < ApplicationRecord
  has_one :adress_info
  has_one :near_street
  has_one :intersection
  has_one :excavation_info
end

app/models/excavation_info.rb
class ExcavationInfo < ApplicationRecord
    def project_start_date
        super.strftime('%Y/%m/%d %H:%M:%S')
    end

    def digsite_info
        loader = Dataloader.new do |ids|
            digsite_infos = DigsiteInfo.find(*ids)
            [digsite_infos]
        end
        if self.digsite_infos_id.eql? nil
            return {}
        end
        promise = loader.load(self.digsite_infos_id)
        promise.sync
    end
end

app/models/excavator.rb
class Excavator < ApplicationRecord
    has_many :field_contact
    has_one :contact
end

app/models/field_contact.rb
class FieldContact < ApplicationRecord
end

app/models/intersection.rb
class Intersection < ApplicationRecord
  has_one :itoi
end

app/models/itoi.rb
class Itoi < ApplicationRecord
end

app/models/near_street.rb
class NearStreet < ApplicationRecord
end

app/models/primary_service_area_code.rb
class PrimaryServiceAreaCode < ApplicationRecord
end

app/models/service_area.rb
class ServiceArea < ApplicationRecord
    has_one :primary_service_area_code
    has_one :additional_service_area_code

    
    def primary_service_area
        loader = Dataloader.new do |ids|
            [PrimaryServiceAreaCode.find(*ids)]
        end
        if self.primary_service_area_codes_id.eql? nil
            return {}
        end
        promise = loader.load(self.primary_service_area_codes_id)
        promise.sync
    end

    def additional_service_area
        loader = Dataloader.new do |ids|
            [AdditionalServiceAreaCode.find(*ids)]
        end
        if self.additional_service_area_codes_id.eql? nil
            return {}
        end
        promise = loader.load(self.additional_service_area_codes_id)
        promise.sync
    end
end

app/models/street_digsite.rb
class StreetDigsite < ApplicationRecord
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    has_one :ticket_date
    has_one :service_area
    has_one :excavator

    def ticket_dates
        loader = Dataloader.new do |ids|
            ticket_dates = TicketDates.find(*ids)
            self.format(ticket_dates)
        end
        if self.ticket_dates_id.eql? nil
            return {}
        end
        promise = loader.load(self.ticket_dates_id)
        promise.sync
    end

    def excavation_info
        loader = Dataloader.new do |ids|
            excavation_infos = ExcavationInfo.find(*ids)
            [excavation_infos]
        end
        if self.excavation_info_id.eql? nil
            return {}
        end
        promise = loader.load(self.excavation_info_id)
        promise.sync
    end

    def service_areas
        loader = Dataloader.new do |ids|
            service_areas = ServiceArea.find(*ids)
            self.format_service_areas(service_areas)
        end
        if self.service_areas_id.eql? nil
            return {}
        end
        promise = loader.load(self.service_areas_id)
        promise.sync
    end

    private

    def format(ticket_dates)
        [
            RequestTakenDateTime: ticket_dates.request_taken_date_time,
            ResponseDueDateTime: ticket_dates.response_due_date_time,
            LegalDateTime: ticket_dates.legal_date_time,
            RestakeDate: ticket_dates.restake_date,
            ExpirationDate: ticket_dates.expiration_date,
            LPMmettingAcceptDueDate: ticket_dates.lpm_metting_accept_due_date,
            OverheadBeginDate: ticket_dates.overhead_begin_date,
            OverheadEndDate: ticket_dates.overhead_end_date,
            TransmissionDateTime: ticket_dates.transmission_date_time
        ]
    end

    def format_service_areas(service_areas)
        [
            PrimaryServiceAreaCode: service_areas.primary_service_area,
            AdditionalServiceAreaCodes: service_areas.additional_service_area
        ]
    end
end

app/models/ticket_dates.rb
class TicketDates < ApplicationRecord
    def response_due_date_time
        super.strftime('%Y/%m/%d %H:%M:%S')
    end

    def transmission_date_time
        super.strftime('%Y/%m/%d %H:%M:%S')
    end

    def legal_date_time
        super.strftime('%Y/%m/%d %H:%M:%S')
    end

    def request_taken_date_time
        super.strftime('%Y/%m/%d %H:%M:%S')
    end

    def restake_date
        super.strftime('%Y/%m/%d %H:%M:%S')
    end

    def expiration_date
        super.strftime('%Y/%m/%d %H:%M:%S')
    end

    def lpm_metting_accept_due_date
        super.strftime('%Y/%m/%d %H:%M:%S')
    end

    def overhead_begin_date
        super.strftime('%Y/%m/%d %H:%M:%S')
    end

    def overhead_end_date
        super.strftime('%Y/%m/%d %H:%M:%S')
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show ]

  def index
    @tickets = Ticket.all
  end

  def create
    render :json => {
      data: JSONBuilder::Ticket.call(Trees::Ticket::Build.new(params["data"]).call)
      }
  rescue => e
    render :json => {
      error: "Please check your params",
      status: 400
    }
  end

  def show
    respond_to do |format|
      format.html { 
        render :show
      }
      format.json { 
        render :json => { data: JSONBuilder::Ticket.call(@ticket) } 
      }
    end
  end

  private
    def set_ticket
      @ticket = Ticket.find(params[:id])
      @digsite_info = @ticket.excavation_info.digsite_info
      @adress_info = AdressInfo.find(@digsite_info.adress_info_id)
      @polygon = @digsite_info.polygon.coordinates.first

    rescue => e
      render :json => {
        error: "Records Not Found",
        status: 404
      }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Solution</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :requestNumber, style: "display: block" %>
    <%= form.text_area :requestNumber %>
  </div>

  <div>
    <%= form.label :sequenceNumber, style: "display: block" %>
    <%= form.number_field :sequenceNumber %>
  </div>

  <div>
    <%= form.label :requestType, style: "display: block" %>
    <%= form.text_area :requestType %>
  </div>

  <div>
    <%= form.label :requestAction, style: "display: block" %>
    <%= form.text_area :requestAction %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Show this ticket", @ticket %> |
  <%= link_to "Back to tickets", tickets_path %>
</div>

app/views/tickets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tickets</h1>

<div id="tickets">
  <% @tickets.each do |ticket| %>
    <%= render ticket %>
    <p>
      <%= link_to "Show this ticket", ticket %>
    </p>
  <% end %>
</div>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Back to tickets", tickets_path %>
</div>

app/views/tickets/show.html.erb
<p style="color: green"><%= notice %></p>

Polygon data : <%= @polygon %>
</br>Place : <%= @adress_info.place %>
</br>County : <%= @adress_info.county %>
</br> State : <%= @adress_info.state %>

<div>
<%= area_map [{geometry: {type: "Polygon", coordinates: [@polygon]}}],color: "#6F255D" %>
</div>